# ===============================
# Force truecolor
# ===============================
export COLORTERM=truecolor
export TERM=xterm-kitty


# ===============================
# Lines configured by zsh-newuser-install
# ===============================
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install


# ===============================
# Lines added by compinstall
# ===============================
zstyle :compinstall filename '$HOME/.zshrc'


# ===============================
# Enable Spaceship prompt
# ===============================
autoload -U promptinit; promptinit
prompt spaceship


# ===============================
# Spaceship config
# ===============================
SPACESHIP_PROMPT_ORDER=(
  user
  dir
  git
  exec_time
  line_sep
  char
)

SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "

SPACESHIP_DIR_TRUNC=3
SPACESHIP_GIT_BRANCH_COLOR="white"
SPACESHIP_GIT_STATUS_COLOR="white"

SPACESHIP_USER_SHOW=always
SPACESHIP_HOST_SHOW=false

SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_THRESHOLD=2


autoload -Uz compinit
compinit
# End of lines added by compinstall


# ===============================
# Aliases
# ===============================
alias cmatrix='cmatrix -C white -a -b -u 6'


# ===============================
# Initialize syntax highlighting
# ===============================
ZSH_HIGHLIGHT_MAXLENGTH=512
typeset -gA ZSH_HIGHLIGHT_STYLES


# ===============================
# Syntax highlighting
# ===============================
# Terminal palette names only (no hex), so the colours follow the current
# theme: kitty's colour0-15 are set by invictus-theme.
# Base text and arguments stay in the terminal foreground (marble).
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[command]='fg=cyan,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=white'
ZSH_HIGHLIGHT_STYLES[alias]='fg=white'
ZSH_HIGHLIGHT_STYLES[function]='fg=white'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=blue'
ZSH_HIGHLIGHT_STYLES[argument]='none'
ZSH_HIGHLIGHT_STYLES[options]='fg=blue,bold'
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[quoted]='fg=green'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=green'
ZSH_HIGHLIGHT_STYLES[variable]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[assign]='fg=white'
ZSH_HIGHLIGHT_STYLES[comment]='fg=8'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red'

# ===============================
# Autosuggestions
# ===============================
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


# ===============================
# Colored coreutils
# ===============================
eval "$(dircolors -b)"

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'


# ===============================
# Syntax highlighting (must be last plugin)
# ===============================
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# ===============================
# Fastfetch (interactive only)
# ===============================
[[ $- == *i* ]] && fastfetch
