-- Generated by invictus-theme from theme "{{meta.name}}". Do not edit.
-- look.lua does: local c = dofile(HOME .. "/.config/invictus/current/hyprland-colors.lua")
-- Values are Hyprland colour strings; c.sol is the focus colour.
return {
    id         = "{{meta.id}}",
    night      = "rgb({{night|hex}})",
    basalt     = "rgb({{basalt|hex}})",
    stone      = "rgb({{stone|hex}})",
    line       = "rgb({{line|hex}})",
    marble     = "rgb({{marble|hex}})",
    parchment  = "rgb({{parchment|hex}})",
    ash        = "rgb({{ash|hex}})",
    sol        = "rgb({{sol|hex}})",
    sol_bright = "rgb({{sol-bright|hex}})",
    pompeii    = "rgb({{pompeii|hex}})",
    laurel     = "rgb({{laurel|hex}})",
    lapis      = "rgb({{lapis|hex}})",
    verdigris  = "rgb({{verdigris|hex}})",
    tyrian     = "rgb({{tyrian|hex}})",
}
