#!/usr/bin/env python3
"""Checks for tests/iso/disk-boot.py without QEMU: its limine.conf logic on
sample files (and the real sed), and its verdicts against a fake root shell
(tests/iso/fake_shell.py) that can reboot into a second set of answers.

    python3 tests/iso/disk-boot-rules.py     ok/FAIL lines, exit 1 on any failure
"""
import importlib.util
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
DRIVER = os.path.join(HERE, "disk-boot.py")
sys.dont_write_bytecode = True
sys.path.insert(0, HERE)
from fake_shell import serve  # noqa: E402

spec = importlib.util.spec_from_file_location("disk_boot", DRIVER)
db = importlib.util.module_from_spec(spec)
spec.loader.exec_module(db)

passed = failed = 0


def check(name, ok, detail=""):
    global passed, failed
    print(("ok    " if ok else "FAIL  ") + name)
    if ok:
        passed += 1
    else:
        failed += 1
        if detail:
            print(detail)


UUID = "0f3c2a51-7d4e-4b8e-9b61-2f1d0c5e8a77"
CMD = f"root=UUID={UUID} rootflags=subvol=/@ rw quiet splash"
SNAP1 = f"root=UUID={UUID} rootflags=subvol=/@snapshots/1/snapshot rw quiet splash"
SNAP12 = f"root=UUID={UUID} rootflags=subvol=/@snapshots/12/snapshot rw quiet splash"
HEADER = """### Invictus start-up menu.
timeout: 3
default_entry: 2
remember_last_entry: no
hash_mismatch_panic: no
interface_branding: Invictus
"""
# limine-entry-tool's entry (format from a real run, 2026-09-30) ...
FIRST = HEADER + f"""
/+Invictus
  comment: Invictus
  //linux-cachyos
    protocol: linux
    path: boot():/4f1c/linux-cachyos/vmlinuz#9d2e
    module_path: boot():/4f1c/linux-cachyos/initramfs#77ab
    cmdline: {CMD}
"""
# ... plus limine-snapper-sync's Snapshots folder (LimineWriter.java 1.32.0:
# "//Snapshots" in the OS folder, "///<id> │ <time>", "////<kernel>").
SYNCED = FIRST + f"""  //Snapshots
    ### Auto-generated by limine-snapper-sync
    comment: 2 / 8 snapshots
    ///12 │ 2026-10-08 11:00:00
      comment: pacman -S cowsay
      ////linux-cachyos
        protocol: linux
        path: boot():/4f1c/limine_history/vmlinuz-linux-cachyos_sha256_aa
        module_path: boot():/4f1c/limine_history/initramfs-linux-cachyos_sha256_bb
        cmdline: {SNAP12}
    ///1  │ 2026-10-08 10:00:00
      comment: Fresh install
      ////linux-cachyos
        protocol: linux
        path: boot():/4f1c/limine_history/vmlinuz-linux-cachyos_sha256_cc
        module_path: boot():/4f1c/limine_history/initramfs-linux-cachyos_sha256_dd
        cmdline: {SNAP1}
"""

# ---- limine.conf logic ---------------------------------------------------------------------
ents = db.parse_limine(SYNCED)
check("parse: every entry line, none of the comments or options",
      [(e["depth"], e["name"]) for e in ents] == [
          (1, "Invictus"), (2, "linux-cachyos"), (2, "Snapshots"), (3, "12 │ 2026-10-08 11:00:00"),
          (4, "linux-cachyos"), (3, "1  │ 2026-10-08 10:00:00"), (4, "linux-cachyos")],
      repr([(e["depth"], e["name"]) for e in ents]))
check("parse: folders are entries with deeper entries under them",
      [e["dir"] for e in ents] == [True, False, True, True, False, True, False])
m = db.main_entry(ents, "linux-cachyos")
check("the normal entry is the linux-cachyos entry outside Snapshots", m is not None and db.cmdline_of(m) == CMD)
check("no normal entry for a kernel the file does not boot", db.main_entry(ents, "linux-lts") is None)
s1 = db.snapshot_entry(ents, 1)
check("snapshot 1's entry is found by its command line, not snapshot 12's",
      s1 is not None and db.cmdline_of(s1) == SNAP1)
check("no entry for a snapshot that is not there", db.snapshot_entry(ents, 2) is None)
check("before the sync there is no snapshot entry", db.snapshot_entry(db.parse_limine(FIRST), 1) is None)
check("a /@ command line is not a snapshot", db.snapshot_number(m) is None)
check("same_cmdline: a loader's BOOT_IMAGE= is ignored",
      db.same_cmdline("BOOT_IMAGE=/vmlinuz " + CMD, CMD))
check("same_cmdline: a missing or extra parameter is a different command line",
      not db.same_cmdline(CMD + " single", CMD) and not db.same_cmdline(CMD.replace(" quiet", ""), CMD))

index, sed = db.default_entry_sed(SYNCED, s1)
check("default_entry: snapshot 1's kernel is entry 7 with every folder open", index == 7, str(index))
with tempfile.TemporaryDirectory() as d:
    f = os.path.join(d, "limine.conf")
    with open(f, "w") as fh:
        fh.write(SYNCED)
    p = subprocess.run(["sed", "-i", *sed, f], capture_output=True, text=True)
    edited = open(f).read()
after = db.parse_limine(edited)
check("the real sed applies the edit", p.returncode == 0, p.stderr)
check("after the edit every folder is open and nothing else changed name",
      all(e["expanded"] for e in after if e["dir"]) and not any(e["expanded"] for e in after if not e["dir"])
      and [e["name"] for e in after] == [e["name"] for e in ents],
      edited)
check("after the edit default_entry names snapshot 1's kernel",
      "default_entry: 7" in edited.splitlines() and edited.count("default_entry") == 1
      and db.cmdline_of(after[7 - 1]) == SNAP1, edited)
check("the edit keeps every option line", [e["options"] for e in after] == [e["options"] for e in ents])
no_default = SYNCED.replace("default_entry: 2\n", "")
i2, sed2 = db.default_entry_sed(no_default, db.snapshot_entry(db.parse_limine(no_default), 1))
p = subprocess.run(["sed", *sed2], input=no_default, capture_output=True, text=True)
check("a file without default_entry gets one", p.stdout.splitlines()[0] == f"default_entry: {i2}", p.stdout[:200])

# ---- verdicts against a fake shell ---------------------------------------------------------
KERNEL = "6.17.1-2-cachyos"
ENV = f"kernel={KERNEL}\nkernel_pkgbase=linux-cachyos\nroot_uuid={UUID}\nrails=custodia\nuser=maria\n"
SNAPPER = (" # │ Type   │ Pre # │ Date                     │ User │ Cleanup │ Description   │ Userdata\n"
           "───┼────────┼───────┼──────────────────────────┼──────┼─────────┼───────────────┼──────────\n"
           " 0 │ single │       │                          │ root │         │ current       │\n"
           " 1 │ single │       │ Thu Oct  8 10:00:00 2026 │ root │ number  │ Fresh install │ important=yes\n")
STATUS = ("rails=custodia\neffective=custodia\nuntil=\nsince=\nby=\nfull-access=off\nai=off\n"
          "net.home=on\n")
BOOT1 = {
    "stty": (0, ""),
    "systemctl is-system-running": (0, "running\n"),
    "cat /proc/sys/kernel/random/boot_id": (0, "aaaa-1111\n"),
    "uname -r": (0, KERNEL + "\n"),
    "cat /proc/cmdline": (0, CMD + "\n"),
    "cat /boot/limine.conf": (0, SYNCED),
    "tr -d": (0, "Limine 10.1.0\n"),
    "systemctl get-default": (0, "graphical.target\n"),
    "systemctl is-active graphical.target": (0, "active\n"),
    "systemd-analyze time": (0, "Startup finished in 2.1s (firmware) + 3s (loader) + 1.2s (kernel) + 4s (userspace)"
                                " = 10.3s\ngraphical.target reached after 4s in userspace.\n"),
    "systemctl is-active display-manager.service": (0, "active\n"),
    "systemctl --failed": (0, ""),
    "systemctl list-jobs": (0, "No jobs running.\n"),
    "journalctl": (0, "[ 1.0] maria-invictus systemd[1]: Started Getty on tty1.\n"),
    "snapper --no-dbus -c root list": (0, SNAPPER),
    "systemctl list-sockets": (0, "/run/dbus/system_bus_socket dbus.socket dbus.service\n"),
    "systemctl is-active sshd.service": (3, "inactive\n"),
    "ss -Hlp": (0, 'u_str LISTEN 0 4096 /run/dbus/system_bus_socket 1 * 0 users:(("dbus-broker",pid=300,fd=3))\n'),
    "invictus-sys guardrails status": (0, STATUS),
    "invictus-sys guardrails check": (0, "consistent: custodia\n"),
    "systemd-analyze blame": (0, "1.0s NetworkManager.service\n"),
    "systemctl stop limine-snapper-sync": (0, ""),
    "sed -i": (0, ""),
}
BOOT2 = {
    "stty": (0, ""),
    "cat /proc/sys/kernel/random/boot_id": (0, "bbbb-2222\n"),
    "systemctl is-system-running": (1, "degraded\n"),
    "cat /proc/cmdline": (0, SNAP1 + "\n"),
    "systemctl is-active multi-user.target": (0, "active\n"),
    "findmnt": (0, "overlay overlay\n"),
    "systemctl --failed": (0, "snapper-cleanup.service loaded failed failed Daily Cleanup of Snapper Snapshots\n"),
    "systemctl list-jobs": (0, "No jobs running.\n"),
    "journalctl": (0, ""),
}


def scenario(name, b1=None, b2=None, want_rc=0, want_text=(), not_text=(), args=(), timeout=25, env=ENV):
    boot1 = dict(BOOT1)
    boot1.update(b1 or {})
    boot2 = dict(BOOT2)
    boot2.update(b2 or {})
    seen = []
    # After the driver's sed, limine.conf reads back with default_entry: 7.
    base_conf = boot1["cat /boot/limine.conf"]

    class Answers(dict):
        def items(self):
            for k, v in dict.items(self):
                if k == "cat /boot/limine.conf" and v is not None and v == base_conf:
                    if any(c.startswith("sed -i") for c in seen):
                        v = (0, base_conf[1].replace("default_entry: 2", "default_entry: 7"))
                yield k, v

    with tempfile.TemporaryDirectory() as d:
        with open(os.path.join(d, "disk.env"), "w") as f:
            f.write(env)
        srv = serve(os.path.join(d, "shell.sock"), [Answers(boot1), boot2], seen)
        p = subprocess.run([sys.executable, DRIVER, d, "--env", os.path.join(d, "disk.env"),
                            "--timeout", str(timeout), "--sync-wait", "2", *args],
                           capture_output=True, text=True, timeout=timeout * 2 + 300)
        srv.close()
    text = p.stdout + p.stderr
    ok = (p.returncode == want_rc and all(t in text for t in want_text)
          and not any(t in text for t in not_text))
    check(name, ok, text)
    return seen


seen = scenario("a clean install boots, then boots its Fresh install snapshot", want_rc=0,
                want_text=["limine booted the //linux-cachyos entry", "snapshot 1: Fresh install",
                           "limine.conf boots snapshot 1", "guard rails: custodia, full-access off",
                           "default_entry: 7 (snapshot 1)", "snapshot boot: multi-user.target reached",
                           "note  snapshot boot: failed units:", "disk boot: passed"])
check("the clean run stopped limine-snapper-sync before editing and edited with sed",
      any(c.startswith("systemctl stop limine-snapper-sync") for c in seen)
      and any(c.startswith("sed -i") and "/boot/limine.conf" in c for c in seen))
seen = scenario("--no-snapshot-boot checks the first boot only", args=["--no-snapshot-boot"],
                want_text=["snapshot boot skipped", "disk boot: passed"], not_text=["rebooting"])
check("--no-snapshot-boot never edits limine.conf", not any(c.startswith("sed -i") for c in seen))
scenario("another kernel fails", {"uname -r": (0, "6.17.1-arch1-1\n")}, want_rc=1,
         want_text=["FAIL  running kernel 6.17.1-arch1-1, expected the image's CachyOS kernel"])
scenario("a command line that is not the limine entry's fails (limine picked another entry)",
         {"cat /proc/cmdline": (0, CMD + " systemd.debug_shell=/dev/ttyS1\n")}, want_rc=1,
         want_text=["FAIL  /proc/cmdline is not the linux-cachyos entry's command line"])
scenario("a limine.conf with no linux-cachyos entry fails",
         {"cat /boot/limine.conf": (0, HEADER)}, want_rc=1,
         want_text=["FAIL  /boot/limine.conf has no linux-cachyos entry"])
scenario("another root file system fails",
         {"cat /proc/cmdline": (0, CMD.replace(UUID, "1234") + "\n"),
          "cat /boot/limine.conf": (0, SYNCED.replace(UUID, "1234"))}, want_rc=1,
         want_text=["FAIL  /proc/cmdline does not name the image's root"])
scenario("a failed unit fails",
         {"systemctl is-system-running": (1, "degraded\n"),
          "systemctl --failed": (0, "sddm.service loaded failed failed Simple Desktop Display Manager\n")},
         want_rc=1, want_text=["FAIL  first boot: failed units:", "sddm.service"])
scenario("a PID 1 timeout in the journal fails",
         {"journalctl": (0, "[ 95.0] h systemd[1]: Timed out waiting for device /dev/disk/by-uuid/AB12.\n")},
         want_rc=1, want_text=["FAIL  first boot: journal:", "Timed out waiting for device"])
scenario("a boot that never finishes fails",
         {"systemctl is-system-running": None,
          "systemctl list-jobs": (0, "7 systemd-fsck@dev-disk.service start running\n")},
         want_rc=1, timeout=8, want_text=["FAIL  first boot: boot not finished within 8 s"])
scenario("the default target not reached fails (systemd-analyze)",
         {"systemd-analyze time": (1, "Bootup is not yet finished.\n")}, want_rc=1,
         want_text=["FAIL  default target graphical.target not reached"])
scenario("an inactive default target fails",
         {"systemctl is-active graphical.target": (3, "inactive\n")}, want_rc=1,
         want_text=["FAIL  default target graphical.target not reached (is-active: inactive)"])
scenario("no login screen fails",
         {"systemctl is-active display-manager.service": (3, "inactive\n")}, want_rc=1,
         want_text=["FAIL  the display manager (login screen) is not running"])
scenario("no Fresh install snapshot fails",
         {"snapper --no-dbus -c root list": (0, SNAPPER.replace("Fresh install", "something else"))},
         want_rc=1, want_text=["FAIL  snapper's root config has no \"Fresh install\" snapshot"])
scenario("no limine-snapper-sync entry fails (after waiting)",
         {"cat /boot/limine.conf": (0, FIRST), "systemctl is-active limine-snapper-sync": (0, "active\n")},
         want_rc=1, want_text=["FAIL  /boot/limine.conf has no limine-snapper-sync entry for snapshot 1",
                               "snapshot boot not tried"])
scenario("an entry for another snapshot is not the Fresh install entry",
         {"cat /boot/limine.conf": (0, SYNCED.replace("@snapshots/1/snapshot", "@snapshots/3/snapshot"))},
         want_rc=1, want_text=["FAIL  /boot/limine.conf has no limine-snapper-sync entry for snapshot 1"])
scenario("an ssh socket fails (the generator mask is missing)",
         {"systemctl list-sockets": (0, "/run/ssh-unix-local/socket sshd-unix-local.socket sshd-unix-local@.service\n")},
         want_rc=1, want_text=["FAIL  an ssh socket is listening:", "sshd-unix-local.socket"])
scenario("a running sshd fails", {"systemctl is-active sshd.service": (0, "active\n")}, want_rc=1,
         want_text=["FAIL  sshd.service is active"])
scenario("sshd listening on a port fails",
         {"ss -Hlp": (0, 'tcp LISTEN 0 128 0.0.0.0:22 0.0.0.0:* users:(("sshd",pid=411,fd=3))\n')},
         want_rc=1, want_text=["FAIL  sshd is listening:"])
scenario("Libertas on a Custodia install fails",
         {"invictus-sys guardrails status": (0, STATUS.replace("=custodia", "=libertas"))}, want_rc=1,
         want_text=["FAIL  guard rails are not custodia"])
scenario("Custodia with full access on fails",
         {"invictus-sys guardrails status": (0, STATUS.replace("full-access=off", "full-access=on"))},
         want_rc=1, want_text=["FAIL  Custodia with the assistant's full access on"])
scenario("derived files out of step fail (guardrails check)",
         {"invictus-sys guardrails check": (1, "would change /etc/sudoers.d/40-invictus-guardrails\n")},
         want_rc=1, want_text=["FAIL  invictus-sys guardrails check", "40-invictus-guardrails"])
scenario("no guardrails command at all fails",
         {"invictus-sys guardrails status": (127, "sh: invictus-sys: command not found\n"),
          "invictus-sys guardrails check": (127, "sh: invictus-sys: command not found\n")},
         want_rc=1, want_text=["FAIL  guard rails are not custodia"])
scenario("a snapshot boot that lands on the normal entry fails",
         b2={"cat /proc/cmdline": (0, CMD + "\n")}, want_rc=1,
         want_text=["FAIL  default_entry 7 did not boot snapshot 1"])
scenario("a snapshot boot that lands on another snapshot fails",
         b2={"cat /proc/cmdline": (0, SNAP12 + "\n")}, want_rc=1,
         want_text=["FAIL  default_entry 7 did not boot snapshot 1"])
scenario("a snapshot boot short of multi-user fails",
         b2={"systemctl is-active multi-user.target": (3, "inactive\n")}, want_rc=1,
         want_text=["FAIL  the snapshot boot did not reach multi-user.target"])
scenario("a snapshot boot that never comes back fails",
         b2={"stty": None, "cat /proc/sys/kernel/random/boot_id": None}, want_rc=1, timeout=12,
         want_text=["FAIL  the snapshot boot did not come up within 12 s"])
scenario("a reboot that never happens fails (the old boot's shell still answers, same boot id)",
         b2=dict(BOOT1, **{"systemctl is-active multi-user.target": (0, "active\n")}), want_rc=1, timeout=12,
         want_text=["FAIL  the snapshot boot did not come up within 12 s"], not_text=["did not boot snapshot"])
scenario("a failed sed fails before rebooting",
         {"sed -i": (4, "sed: couldn't open temporary file /boot/sedX: Read-only file system\n")}, want_rc=1,
         want_text=["FAIL  could not make entry 7 limine's default"], not_text=["rebooting"])
scenario("no root shell at all fails",
         {"stty": None, "systemctl": None, "cat": None, "uname": None}, want_rc=1, timeout=6,
         want_text=["FAIL  no root shell on the second serial port within 6 s"])
scenario("a disk.env without the kernel is refused", env="rails=custodia\n", want_rc=1,
         want_text=["has no kernel="])

print(f"\ndisk-boot rules: {passed} passed, {failed} failed")
sys.exit(1 if failed else 0)
