title    Invictus, Advanced install
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% %KERNEL_PARAMS% quiet splash invictus.install=advanced
