# shellcheck shell=bash
# ------------------------------------------------------------
# Shipped desktop defaults and where they go in a home.
# Shared by first-login.sh, invictus-doctor.sh and dev/adopt.sh;
# installed as /usr/lib/invictus/lib/defaults.sh by invictus-tools.
#
# invictus-desktop ships the defaults under $INVICTUS_SHARE/config,
# laid out like ~/.config, except shell/zshrc which is ~/.zshrc.
# first-login copies each one into the home only if it is absent and
# records the sha256 it copied in $STATE/defaults.sha256, so the doctor
# can later tell "you changed it" from "the default changed".
# ------------------------------------------------------------

INVICTUS_SHARE="${INVICTUS_SHARE:-/usr/share/invictus}"

invictus_state_dir() {
    printf '%s\n' "${INVICTUS_STATE:-${XDG_STATE_HOME:-$HOME/.local/state}/invictus}"
}

# Home path for a default, given its path relative to $INVICTUS_SHARE/config.
default_user_path() {
    case "$1" in
        shell/zshrc) printf '%s\n' "$HOME/.zshrc" ;;
        *) printf '%s\n' "${XDG_CONFIG_HOME:-$HOME/.config}/$1" ;;
    esac
}

# Every shipped default, relative, sorted.
default_files() {
    [[ -d "$INVICTUS_SHARE/config" ]] || return 0
    (cd "$INVICTUS_SHARE/config" && find . -type f | sed 's#^\./##' | LC_ALL=C sort)
}

# Templates that become the user's own file: never replaced once they exist.
default_user_owned() {
    case "$1" in
        hypr/monitors.lua|hypr/user.lua) return 0 ;;
    esac
    return 1
}

# What dev/adopt.sh replaces in an existing home (after a backup): the
# desktop pieces that name installed paths or carry the look. Shell,
# editor and tool preferences (zshrc, zed, btop, cava, fastfetch) stay
# the user's; invictus-doctor lists how they differ.
default_adopt_replaces() {
    case "$1" in
        hypr/*|waybar/*|rofi/*|kitty/*|swaync/*) return 0 ;;
    esac
    return 1
}

# Hyprland writes an example hyprland.lua when it starts and finds no
# config (src/config/lua/DefaultConfig.hpp). If it won the race with
# first-login, that file is not the user's work.
is_autogenerated_hypr() {
    [[ -f "$1" ]] && head -c 600 "$1" | grep -q 'AUTOGENERATED HYPRLAND CONFIG'
}

file_sha() { sha256sum < "$1" | cut -d' ' -f1; }

# The sha256 first-login recorded for a default, or nothing.
recorded_default() {
    local db
    db="$(invictus_state_dir)/defaults.sha256"
    [[ -f "$db" ]] || return 0
    awk -v p="$1" '$2 == p { print $1 }' "$db" | tail -1
}

record_default() {
    local db tmp
    db="$(invictus_state_dir)/defaults.sha256"
    mkdir -p "$(dirname "$db")"
    tmp="$db.tmp.$$"
    { [[ -f "$db" ]] && awk -v p="$2" '$2 != p' "$db"; printf '%s %s\n' "$1" "$2"; } > "$tmp"
    mv "$tmp" "$db"
}
