#!/usr/bin/env bash
# ------------------------------------------------------------
# invictus-first-login: set up a home for the Invictus desktop.
# Installed as /usr/lib/invictus/first-login and run once per user by
# the invictus-first-login user unit (invictus-desktop enables it for
# everyone). Replaces legacy/init-user.sh and keeps its logic.
#
#   first-login                 once: home folders, XDG dirs, user
#                               services, caches, then copy each shipped
#                               default that is not in the home yet
#   first-login --dry-run       print what it would do, change nothing
#   first-login --adopt DIR     (dev/adopt.sh) also replace the desktop
#                               defaults that differ (hypr, waybar, rofi,
#                               kitty, swaync), after copying the old file
#                               into DIR, and switch Hyprland to hyprland.lua
#
# Never overwrites a file without a backup, and never a user.lua or
# monitors.lua that exists. Without --adopt it only adds missing files,
# with two rules:
#  - a home that runs Hyprland from hyprland.conf does not get a
#    hyprland.lua (Hyprland prefers .lua, so adding one would switch the
#    desktop silently; dev/adopt.sh does that switch on purpose);
#  - a hyprland.lua that Hyprland autogenerated (it starts before this
#    unit on a brand-new account) is backed up and replaced.
# Sentinel: ~/.local/state/invictus/first-login.done
# ------------------------------------------------------------
set -euo pipefail

LIB="${INVICTUS_LIB:-/usr/lib/invictus}"
# shellcheck source=scripts/lib/defaults.sh
. "${INVICTUS_DEFAULTS_SH:-$LIB/lib/defaults.sh}"

DRY=false
ADOPT_DIR=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY=true; shift ;;
        --adopt) ADOPT_DIR="${2:?--adopt needs a backup folder}"; shift 2 ;;
        -h|--help) sed -n '2,27p' "$0"; exit 0 ;;
        *) echo "first-login: unknown argument $1" >&2; exit 2 ;;
    esac
done

STATE="$(invictus_state_dir)"
SENTINEL="$STATE/first-login.done"
STAMP="$(date +%Y%m%d-%H%M%S)"
CFG="${XDG_CONFIG_HOME:-$HOME/.config}"

say() { echo "first-login: $*"; }
run() { if $DRY; then say "would run: $*"; else "$@"; fi; }

if [[ -f "$SENTINEL" && -z "$ADOPT_DIR" ]]; then
    say "already done ($SENTINEL)"
    exit 0
fi

# ---- the old init-user.sh, unless that already ran on this home -------------
if [[ -z "$ADOPT_DIR" && ! -f "$HOME/.local/state/invictus-initialized" \
      && ! -f "$HOME/.local/state/hyprdots-initialized" ]]; then
    say "creating home folders"
    run mkdir -p "$HOME/Repos" "$HOME/Projects" "$HOME/Documents" "$HOME/Downloads" \
        "$HOME/Screenshots" "$HOME/Pictures/Wallpapers" "$HOME/.local/bin" "$HOME/.cache"
    if command -v xdg-user-dirs-update >/dev/null; then run xdg-user-dirs-update; fi
    if command -v systemctl >/dev/null; then
        run systemctl --user enable pipewire.service pipewire-pulse.service \
            wireplumber.service xdg-desktop-portal.service || true
    fi
    if command -v fc-cache >/dev/null; then run fc-cache -f || true; fi
fi

# ---- defaults ------------------------------------------------------------------
backup_file() {
    local rel="$1" src="$2" dir="$3"
    run mkdir -p "$(dirname "$dir/$rel")"
    run cp -a "$src" "$dir/$rel"
}

install_default() {
    local rel="$1" dest="$2" sha
    sha="$(file_sha "$INVICTUS_SHARE/config/$rel")"
    run mkdir -p "$(dirname "$dest")"
    run install -m644 "$INVICTUS_SHARE/config/$rel" "$dest"
    $DRY || record_default "$sha" "$rel"
}

added=0 replaced=0 kept=0
while IFS= read -r rel; do
    [[ -n "$rel" ]] || continue
    dest="$(default_user_path "$rel")"
    if [[ ! -e "$dest" && ! -L "$dest" ]]; then
        if [[ "$rel" == hypr/hyprland.lua && -z "$ADOPT_DIR" && -f "$CFG/hypr/hyprland.conf" ]]; then
            say "keeping your hyprland.conf: not adding hyprland.lua (run adopt to switch)"
            kept=$((kept + 1)); continue
        fi
        say "adding $dest"
        install_default "$rel" "$dest"
        added=$((added + 1))
    elif [[ "$rel" == hypr/hyprland.lua ]] && is_autogenerated_hypr "$dest"; then
        say "replacing Hyprland's autogenerated $dest (backup in $STATE/backup/$STAMP)"
        backup_file "$rel" "$dest" "$STATE/backup/$STAMP"
        install_default "$rel" "$dest"
        replaced=$((replaced + 1))
    elif [[ -n "$ADOPT_DIR" ]] && ! default_user_owned "$rel" && default_adopt_replaces "$rel" \
         && ! cmp -s "$dest" "$INVICTUS_SHARE/config/$rel"; then
        say "replacing $dest (old copy in $ADOPT_DIR/$rel)"
        backup_file "$rel" "$dest" "$ADOPT_DIR"
        run rm -f "$dest"
        install_default "$rel" "$dest"
        replaced=$((replaced + 1))
    else
        # Record what we would have copied if it is already identical, so the
        # doctor can follow later changes to this default.
        if ! $DRY && cmp -s "$dest" "$INVICTUS_SHARE/config/$rel" && [[ -z "$(recorded_default "$rel")" ]]; then
            record_default "$(file_sha "$dest")" "$rel"
        fi
        kept=$((kept + 1))
    fi
done < <(default_files)

say "$added added, $replaced replaced, $kept kept as they are"

if ! $DRY; then
    mkdir -p "$STATE"
    date -Is > "$SENTINEL"
fi
