#!/usr/bin/env bash
# ------------------------------------------------------------
# Tests for pkgs/. Needs bash and gpg; runs without makepkg.
#
#   tests/pkgs/run.sh
#
# 1. Every PKGBUILD parses and names itself after its folder.
# 2. The meta packages carry the design 1.2 fixes.
# 3. invictus-keyring: build() derives the trusted fingerprint from
#    the public key; check() refuses the placeholder and any private
#    key. Uses a throwaway key made in a temp dir and deleted after.
# 4. Install trees: package() of every own/meta PKGBUILD, run into temp
#    folders; every installed path the config calls exists there.
# 5. Main compatibility: every repo path that configs deployed from main
#    call (fixtures/main-references.txt) still exists.
# 6. first-login: copy-once, the hyprland.conf rule, Hyprland's
#    autogenerated file, --adopt backups, --dry-run.
# 7. invictus-doctor: defaults classification, --diff, repo order, the
#    stub config check.
# 8. invictus-update: one pacman call, -Syu; no script runs -Sy alone.
# 9. Pinned set and repo file names.
# 10. The hyprlang porter (adopt's monitors.lua and user.lua) on a fake
#    legacy home; its output loads in the stub check.
# 11. AUR pins: header lines, no SKIP, signers' keys; scripts/dev/bump-aur.sh
#    against a fake AUR repo.
# 12, 13. invictus-motion; installer extras (pending-extras).
# 14. invictus-sys: verbs, the polkit policy, Acta, snapshots (MUSTs A2 to
#    A5, A10, A11) with pkexec, snapper and pacman faked at the seam.
# 15. The polkit rules, run in node with polkitd's order and defaults.
# 16. The guard rails: apply, the live switch both ways, timed Libertas,
#    nets, full access, pre-admin-snapshot, the pacman hook (SM9 to SM26).
# 18. First start (invictus-first-boot): run once per person, monitors.lua,
#    look, the assistant step's calls and its key handling, the snapshot.
#
# Needs lua 5.4+ for groups 7 and 10 (LUA=...), node and python3 for 14-16.
# ------------------------------------------------------------
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd -- "$HERE/../.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail=0
ok()   { echo "ok    $1"; }
bad()  { echo "FAIL  $1"; fail=1; }

# Print one field of a PKGBUILD (arrays one item per line).
field() {
    bash -c 'source "$1" >/dev/null; declare -n v="$2"; printf "%s\n" "${v[@]}"' _ "$1" "$2"
}

# ---- 1. every PKGBUILD -----------------------------------------------------
echo "== PKGBUILDs"
n=0
while IFS= read -r pb; do
    dir="$(basename "$(dirname "$pb")")"
    n=$((n + 1))
    if ! bash -n "$pb" 2>"$TMP/err"; then bad "$pb: $(cat "$TMP/err")"; continue; fi
    name="$(field "$pb" pkgname)"
    [[ "$name" == "$dir" ]] || bad "$pb: pkgname '$name' is not the folder name '$dir'"
    [[ -n "$(field "$pb" pkgver)" && -n "$(field "$pb" pkgrel)" ]] || bad "$pb: no pkgver/pkgrel"
    case "$(field "$pb" arch)" in any|x86_64) ;; *) bad "$pb: arch is not 'any' or 'x86_64'" ;; esac
    bash -c 'source "$1"; declare -F package >/dev/null' _ "$pb" || bad "$pb: no package()"
done < <(find "$REPO/pkgs" -name PKGBUILD | sort)
[[ $n -ge 5 ]] || bad "found only $n PKGBUILDs"
[[ $fail == 0 ]] && ok "$n PKGBUILDs parse, named after their folders"
echo

# ---- 2. meta fixes (design 1.2) --------------------------------------------
echo "== meta packages"
m_fail=0
all_deps="$TMP/deps"
for pb in "$REPO"/pkgs/meta/*/PKGBUILD; do field "$pb" depends; done > "$all_deps"
grep -qx vscode "$all_deps" && { bad "vscode is not a package (Microsoft's build is visual-studio-code-bin)"; m_fail=1; }
grep -qx mako "$all_deps"   && { bad "mako is listed; swaync is the notification daemon"; m_fail=1; }
for p in visual-studio-code-bin xwaylandvideobridge discord steam brightnessctl playerctl jq invictus-keyring; do
    grep -qx "$p" "$all_deps" || { bad "$p missing from the metas"; m_fail=1; }
done
dupes="$(for pb in "$REPO"/pkgs/meta/*/PKGBUILD; do field "$pb" depends | sort | uniq -d; done)"
[[ -z "$dupes" ]] || { bad "listed twice in one meta: $dupes"; m_fail=1; }
[[ $m_fail == 0 ]] && ok "visual-studio-code-bin not vscode, no mako, the missing deps added, no duplicates"
echo

# ---- 2b. package sets (docs/packages.md) -------------------------------------
echo "== package sets"
s_fail=0
sbad() { bad "$1"; s_fail=1; }
bare() { sed -e 's/:.*//' -e 's/[<>=].*//' -e '/^$/d'; }
MANIFEST="$REPO/pkgs/meta/sources.txt"
grep -v '^[[:space:]]*\(#\|$\)' "$MANIFEST" > "$TMP/sources"

# Every name a meta or own PKGBUILD depends on (or suggests) is in
# sources.txt, which tests/pkgs/live-arch.sh keeps true against Arch.
for pb in "$REPO"/pkgs/meta/*/PKGBUILD "$REPO"/pkgs/own/*/PKGBUILD; do
    { field "$pb" depends; field "$pb" optdepends; } | bare
done | sort -u > "$TMP/named"
missing="$(cut -d' ' -f1 "$TMP/sources" | sort | comm -13 - "$TMP/named" | paste -sd' ')"
stale="$(cut -d' ' -f1 "$TMP/sources" | sort | comm -23 - "$TMP/named" | paste -sd' ')"
[[ -z "$missing" ]] || sbad "not in pkgs/meta/sources.txt (run tests/pkgs/live-arch.sh --write in Arch): $missing"
[[ -z "$stale" ]] || sbad "sources.txt lists packages no set names: $stale"
while read -r n src; do
    case "$src" in
        core|extra|multilib|aur-paru) ;;
        aur) [[ -f "$REPO/pkgs/aur/$n/PKGBUILD" ]] || sbad "$n: sources.txt says aur, but pkgs/aur/$n does not exist" ;;
        invictus) [[ -f "$REPO/pkgs/own/$n/PKGBUILD" || -f "$REPO/pkgs/meta/$n/PKGBUILD" ]] || sbad "$n: sources.txt says invictus, but no PKGBUILD" ;;
        pinned) grep -hv '^#' "$REPO"/pkgs/pinned/*.lock | cut -d' ' -f1 | grep -x "$n" >/dev/null \
                    || sbad "$n: sources.txt says pinned, but no pkgs/pinned/*.lock lists it" ;;
        *) sbad "$n: unknown source '$src'" ;;
    esac
done < "$TMP/sources"
# Live-ISO-only pins: in the repo for the ISO build, in no set (the
# installer's cleanup job removes them from the installed system).
ISO_ONLY_AUR="calamares"
for d in "$REPO"/pkgs/aur/*/; do
    n="$(basename "$d")"
    if [[ " $ISO_ONLY_AUR " == *" $n "* ]]; then
        grep -q "^$n " "$TMP/sources" && sbad "$n is live-ISO only, but a set names it"
        continue
    fi
    grep -qx "$n aur" "$TMP/sources" || sbad "pkgs/aur/$n is built but no set names it"
done

# One package, one set. The podman trio is in dev and windows on purpose
# (each works alone); a set may depend on another set (invictus-*).
ALLOWED_OVERLAP="podman podman-compose crun"
for pb in "$REPO"/pkgs/meta/*/PKGBUILD; do
    field "$pb" depends | bare | grep -v '^invictus-' | sed "s|\$| $(basename "$(dirname "$pb")")|"
done | sort > "$TMP/placed"
while read -r n; do
    [[ " $ALLOWED_OVERLAP " == *" $n "* ]] && continue
    sbad "$n is in more than one set: $(awk -v n="$n" '$1 == n { print $2 }' "$TMP/placed" | paste -sd' ')"
done < <(cut -d' ' -f1 "$TMP/placed" | uniq -d)
for n in $ALLOWED_OVERLAP; do
    [[ "$(awk -v n="$n" '$1 == n { print $2 }' "$TMP/placed" | paste -sd' ')" == "invictus-dev invictus-windows" ]] \
        || sbad "$n: expected in invictus-dev and invictus-windows only"
done

# Regression, adopt-jack2-conflict (2026-09-30): an existing install has
# jack2 (waybar needs "jack"), and a set that depends on pipewire-jack
# makes pacman --noconfirm refuse the whole update.
for pb in "$REPO"/pkgs/meta/*/PKGBUILD; do
    field "$pb" depends | grep -x pipewire-jack >/dev/null && sbad "adopt-jack2-conflict: $(basename "$(dirname "$pb")") depends on pipewire-jack (optdepends only)"
done

# invictus-base stays off existing installs: no set depends on it, and
# adopt.sh installs only desktop, tessera, gaming, dev.
for pb in "$REPO"/pkgs/meta/*/PKGBUILD; do
    # grep without -q: an early exit would SIGPIPE field, and pipefail
    # would read that as "not found"
    field "$pb" depends | grep -x invictus-base >/dev/null && sbad "$(basename "$(dirname "$pb")") depends on invictus-base"
done
adopt_metas="$(sed -n 's/^for m in \(.*\); do$/\1/p' "$REPO/scripts/dev/adopt.sh")"
[[ "$adopt_metas" == "desktop tessera gaming dev" ]] || sbad "adopt.sh installs '$adopt_metas', want 'desktop tessera gaming dev'"
for f in tessera atrium gaming windows voice moneta; do
    field "$REPO/pkgs/meta/invictus-$f/PKGBUILD" depends | grep -x invictus-desktop >/dev/null || sbad "invictus-$f does not depend on invictus-desktop"
done

# No AI outside the AI set (Alex, 2026-09-30; design-no-ai.md N5, NA3): a
# machine set to No AI has no AI package on disk. Only the AI set's own
# metas may pull one; every other set and own package, followed through
# the invictus-* packages it depends on, must not. The built repo gets the
# same check with pacman's resolver (tests/pkgs/no-ai-in-base.sh).
# shellcheck source=scripts/lib/ai-set.sh
. "$HERE/../../scripts/lib/ai-set.sh"
AI_SETS="$AI_METAS"
pb_of() { local d; for d in meta own; do [[ -f "$REPO/pkgs/$d/$1/PKGBUILD" ]] && { echo "$REPO/pkgs/$d/$1/PKGBUILD"; return; }; done; }
closure() {
    local todo=("$1") seen=" " n pb
    while [[ ${#todo[@]} -gt 0 ]]; do
        n="${todo[0]}"; todo=("${todo[@]:1}")
        [[ "$seen" == *" $n "* ]] && continue
        seen+="$n "; echo "$n"
        pb="$(pb_of "$n")"
        [[ -n "$pb" ]] || continue
        while read -r d; do todo+=("$d"); done < <(field "$pb" depends | bare)
    done
}
n_noai=0
: > "$TMP/noai"
for pb in "$REPO"/pkgs/meta/*/PKGBUILD "$REPO"/pkgs/own/*/PKGBUILD; do
    set_name="$(basename "$(dirname "$pb")")"
    if [[ " $AI_SETS " == *" $set_name "* ]]; then continue; fi
    n_noai=$((n_noai + 1))
    for n in $(closure "$set_name"); do
        if [[ " $AI_PKGS " == *" $n "* ]]; then echo "$set_name pulls $n" >> "$TMP/noai"; fi
    done
    for n in $(field "$pb" optdepends | bare); do
        if [[ " $AI_PKGS " == *" $n "* ]]; then echo "$set_name suggests $n" >> "$TMP/noai"; fi
    done
done
while read -r line; do sbad "no-ai: $line (AI packages belong in $AI_SETS only)"; done < "$TMP/noai"
[[ $n_noai -ge 9 ]] || sbad "no-ai: only $n_noai non-AI sets and own packages checked"
for s in $AI_SETS; do [[ -n "$(pb_of "$s")" ]] || sbad "no-ai: AI set $s has no PKGBUILD"; done

# Commands outside the Hyprland config (fixtures/commands.txt). The
# package must be installed wherever the file is: invictus-desktop, a
# flavour, an own package, or Arch's base; never only invictus-base.
{
    for m in desktop tessera atrium; do field "$REPO/pkgs/meta/invictus-$m/PKGBUILD" depends; done
    for pb in "$REPO"/pkgs/own/*/PKGBUILD; do field "$pb" depends; done
    grep -v '^#' "$HERE/fixtures/arch-base.txt"
    ls "$REPO/pkgs/own"
} | bare | sort -u > "$TMP/desktop-closure"
cut -d' ' -f1 "$TMP/placed" "$TMP/named" | sort -u > "$TMP/anyset"
grep -v '^[[:space:]]*\(#\|$\)' "$HERE/fixtures/commands.txt" > "$TMP/commands"
while read -r cmd pkg file opt; do
    [[ -f "$REPO/$file" ]] || { sbad "commands.txt: no file $file"; continue; }
    needle="$cmd"   # a zsh prompt theme is named, not its file
    [[ "$cmd" =~ /prompt_([a-z0-9_-]+)_setup$ ]] && needle="prompt ${BASH_REMATCH[1]}"
    grep -qF -- "$needle" "$REPO/$file" || sbad "commands.txt: $file does not run $cmd (stale entry?)"
    if [[ "$opt" == optional ]]; then
        grep -qx "$pkg" "$TMP/anyset" || sbad "$cmd ($file): $pkg is in no set"
    else
        grep -qx "$pkg" "$TMP/desktop-closure" || sbad "$cmd ($file): $pkg is not in invictus-desktop, a flavour, our packages or Arch base"
    fi
done < "$TMP/commands"
listed() { awk -v c="$1" -v f="$2" '$1 == c && $3 == f { found = 1 } END { exit !found }' "$TMP/commands"; }
# waybar and swaync: the first word of every command they run; waybar's
# own actions (activate, mode) are not commands
cmds_of_json() {
    grep -oE '"(exec|exec-if|command|on-click[a-z-]*|on-scroll-[a-z]+)": *"([^"\\]|\\.)*"' "$1" \
        | sed -E 's/^"[^"]*": *"//; s/"$//; s/\\"/"/g' \
        | tr '|;&' '\n' | awk '{ print $1 }' | grep -vxE 'activate|mode|' || true
}
seen=0
for f in config/waybar/config.json config/swaync/config.json; do
    while read -r c; do
        seen=$((seen + 1)); listed "$c" "$f" || sbad "$f runs '$c', which fixtures/commands.txt does not map to a package"
    done < <(cmds_of_json "$REPO/$f" | sort -u)
done
# zshrc: sourced files, the prompt theme, $(command ...), and a command after &&
Z=config/shell/zshrc
while read -r c; do
    seen=$((seen + 1)); listed "$c" "$Z" || sbad "$Z runs '$c', which fixtures/commands.txt does not map to a package"
done < <(
    grep -v '^[[:space:]]*#' "$REPO/$Z" | {
        tee >(sed -nE 's/^[[:space:]]*source[[:space:]]+([^[:space:]]+).*/\1/p') \
            >(sed -nE 's/^[[:space:]]*prompt[[:space:]]+([a-z0-9_-]+).*/\/usr\/share\/zsh\/site-functions\/prompt_\1_setup/p') \
            >(grep -oE '\$\([a-z0-9_-]+' | cut -c3-) \
            >(grep -oE '&&[[:space:]]*[a-z0-9_-]+' | sed -E 's/&&[[:space:]]*//') >/dev/null
    } | sort -u
)
[[ $seen -ge 12 ]] || sbad "only $seen commands parsed from waybar, swaync and zshrc; parsing broke?"
# Regression, env-theme-packages (2026-09-30): env.lua names a cursor
# theme and a Qt platform theme; the packages that provide them must be in
# invictus-desktop (env.lua is loaded in every session).
ENV_LUA="$REPO/config/hypr/invictus/env.lua"
env_val() { sed -nE "s/^hl\.env\(\"$1\", *\"([^\"]*)\"\).*/\1/p" "$ENV_LUA"; }
desktop_deps="$(field "$REPO/pkgs/meta/invictus-desktop/PKGBUILD" depends | bare)"
cursor="$(env_val XCURSOR_THEME)"
case "$cursor" in
    Adwaita) cursor_pkg=adwaita-cursors ;;
    '') cursor_pkg="" ;;
    *) cursor_pkg="$cursor" ;;
esac
[[ -z "$cursor_pkg" ]] || grep -qx "$cursor_pkg" <<< "$desktop_deps" \
    || sbad "env-theme-packages: env.lua sets XCURSOR_THEME=$cursor, but invictus-desktop does not depend on $cursor_pkg"
qpa="$(env_val QT_QPA_PLATFORMTHEME)"
case "$qpa" in
    qt5ct|qt6ct) grep -qx "$qpa" <<< "$desktop_deps" || sbad "env-theme-packages: env.lua sets QT_QPA_PLATFORMTHEME=$qpa, but invictus-desktop does not depend on $qpa" ;;
    ''|gtk3|xdgdesktopportal) ;;
    *) sbad "env-theme-packages: QT_QPA_PLATFORMTHEME=$qpa has no package mapping in this test" ;;
esac
[[ -n "$cursor" ]] || sbad "env-theme-packages: no XCURSOR_THEME in env.lua (parsing broke?)"
# The prompt comes from our AUR copy: its PKGBUILD must put it on zsh's fpath.
grep -q 'usr/share/zsh/site-functions/prompt_spaceship_setup' "$REPO/pkgs/aur/spaceship-prompt/PKGBUILD" \
    || sbad "spaceship-prompt no longer installs prompt_spaceship_setup on zsh's fpath"
[[ $s_fail == 0 ]] && ok "$(wc -l < "$TMP/sources") names in sources.txt, one set each, base off adopt, $(wc -l < "$TMP/commands") commands mapped ($seen parsed)"
echo

# ---- 3. invictus-keyring -----------------------------------------------------
echo "== invictus-keyring"
KR="$REPO/pkgs/own/invictus-keyring"

# Run prepare, build and check the way makepkg would, in a copy.
run_keyring() {
    local asc="$1" src="$TMP/src"
    rm -rf "$src"; mkdir -p "$src"
    cp "$asc" "$src/invictus.gpg"
    cp "$KR/invictus-revoked" "$src/"
    ( cd "$src" && srcdir="$src" bash -c 'set -e; source "$1"; prepare; build; check' _ "$KR/PKGBUILD" ) >"$TMP/out" 2>&1
}

export GNUPGHOME="$TMP/keys"
install -dm700 "$GNUPGHOME"
gpg --batch --quiet --passphrase '' --quick-gen-key 'Invictus test key (throwaway)' ed25519 sign never
fpr="$(gpg --with-colons --list-keys 2>/dev/null | awk -F: '/^fpr:/ { print $10; exit }')"
gpg --armor --export "$fpr" > "$TMP/public.asc"
gpg --batch --pinentry-mode loopback --passphrase '' --armor --export-secret-keys "$fpr" > "$TMP/secret.asc"
cat "$TMP/public.asc" "$TMP/secret.asc" > "$TMP/both.asc"
unset GNUPGHOME

k_fail=0
if run_keyring "$TMP/public.asc"; then
    if [[ "$(cat "$TMP/src/invictus-trusted")" == "$fpr:4:" ]]; then :; else
        bad "trusted file is '$(cat "$TMP/src/invictus-trusted")', want '$fpr:4:'"; k_fail=1
    fi
else
    bad "a real public key did not build: $(cat "$TMP/out")"; k_fail=1
fi
cp "$REPO/pkgs/own/invictus-keyring/invictus.gpg" "$TMP/placeholder.asc"
if grep -q INVICTUS-PLACEHOLDER "$TMP/placeholder.asc"; then
    if run_keyring "$TMP/placeholder.asc"; then bad "the placeholder built"; k_fail=1
    elif ! grep -q "still the placeholder" "$TMP/out"; then bad "placeholder refused without saying why: $(cat "$TMP/out")"; k_fail=1; fi
fi
if run_keyring "$TMP/secret.asc"; then bad "a private key built"; k_fail=1
elif ! grep -q "private key material" "$TMP/out"; then bad "private key refused without saying why: $(cat "$TMP/out")"; k_fail=1; fi
if run_keyring "$TMP/both.asc"; then bad "public + private key built"; k_fail=1; fi
echo "not a key" > "$TMP/junk.asc"
if run_keyring "$TMP/junk.asc"; then bad "a file with no key built"; k_fail=1; fi
if grep -q 'PRIVATE KEY' "$KR/invictus.gpg"; then bad "the committed invictus.gpg holds a private key"; k_fail=1; fi
[[ $k_fail == 0 ]] && ok "trusted fingerprint derived from the key; placeholder and private keys refused"
echo

# ---- AUR pins ------------------------------------------------------------------
echo "== AUR pins"
a_fail=0
abad() { bad "$1"; a_fail=1; }
for pb in "$REPO"/pkgs/aur/*/PKGBUILD; do
    d="$(dirname "$pb")"; n="$(basename "$d")"
    grep -qE '^# aur-commit: [0-9a-f]{40} \(' "$pb" || abad "$n: no '# aur-commit: <40-hex sha> (...)' line (scripts/dev/bump-aur.sh reads it)"
    grep -qE '^# Reviewed [0-9]{4}-[0-9]{2}-[0-9]{2} by [A-Z]' "$pb" || abad "$n: no '# Reviewed YYYY-MM-DD by <name>' line"
    grep -qF "# Update: scripts/dev/bump-aur.sh $n" "$pb" || abad "$n: header does not say how to update (scripts/dev/bump-aur.sh $n)"
    # Every source pinned: no SKIP (our git sources carry tree checksums).
    sums="$(bash -c 'source "$1" >/dev/null; for v in ${!sha*} ${!b2*} ${!md5*}; do declare -n a=$v; printf "%s\n" "${a[@]}"; done' _ "$pb")"
    grep -qx SKIP <<< "$sums" && abad "$n: a checksum is SKIP; pin every source"
    srcs="$(bash -c 'source "$1" >/dev/null; for v in ${!source*}; do declare -n a=$v; printf "%s\n" "${a[@]}"; done' _ "$pb")"
    keys="$(field "$pb" validpgpkeys)"
    signed=false
    grep -qE '(\.(sig|asc)$|\?signed$)' <<< "$srcs" && signed=true
    if $signed; then
        [[ -n "$keys" ]] || abad "$n: signed sources but no validpgpkeys"
        for k in $keys; do
            f="$d/keys/pgp/$k.asc"
            [[ -f "$f" ]] || { abad "$n: validpgpkeys $k has no keys/pgp/$k.asc"; continue; }
            gpg --batch --show-keys --with-colons "$f" 2>/dev/null | awk -F: '/^fpr:/ { print $10 }' | grep -qx "$k" \
                || abad "$n: keys/pgp/$k.asc does not hold key $k"
        done
    fi
    for f in "$d"/keys/pgp/*.asc; do
        [[ -f "$f" ]] || continue
        grep -qx "$(basename "$f" .asc)" <<< "$keys" || abad "$n: $(basename "$f") is not in validpgpkeys"
    done
    [[ "$(field "$pb" arch)" == x86_64 || "$(field "$pb" arch)" == any ]] || abad "$n: arch is not x86_64 or any"
done
# claude-code: prepare() refuses a binary the signed manifest does not name
# (makepkg has already checked the manifest's signature by then).
CC="$REPO/pkgs/aur/claude-code/PKGBUILD"
cc_prepare() {  # manifest checksum to write; exit status of prepare()
    local d="$TMP/cc" ver
    rm -rf "$d"; mkdir -p "$d"
    ver="$(field "$CC" pkgver)"
    printf 'not really claude' > "$d/claude-$ver-x86_64"
    printf '{"version":"%s","platforms":{"linux-x64":{"checksum":"%s"}}}' "${2:-$ver}" "$1" > "$d/claude-$ver-manifest.json"
    ( cd "$d" && CARCH=x86_64 bash -c 'set -e; source "$1"; prepare' _ "$CC" ) >/dev/null 2>&1
}
good_sum="$(printf 'not really claude' | sha256sum | cut -d' ' -f1)"
cc_prepare "$good_sum" || abad "claude-code prepare() refused a binary its manifest names"
if cc_prepare "$(printf '0%.0s' {1..64})"; then abad "claude-code prepare() accepted a binary its signed manifest does not name"; fi
if cc_prepare "$good_sum" 0.0.1; then abad "claude-code prepare() accepted a manifest for another version"; fi
# Pins the tests build only in CI's aur-pins job (fixtures/aur-heavy.txt).
while read -r n _; do
    [[ -f "$REPO/pkgs/aur/$n/PKGBUILD" ]] || abad "fixtures/aur-heavy.txt names $n, which is not in pkgs/aur"
done < <(grep -v '^[[:space:]]*\(#\|$\)' "$HERE/fixtures/aur-heavy.txt")

# scripts/dev/bump-aur.sh against a fake AUR repo (file://), no network.
B="$TMP/bump"
mkdir -p "$B/root/scripts/dev" "$B/root/pkgs/aur/demo" "$B/aur"
cp "$REPO/scripts/dev/bump-aur.sh" "$B/root/scripts/dev/"
git -C "$B" init -q aur/demo.git
g() { git -C "$B/aur/demo.git" -c user.name=t -c user.email=t@t "$@"; }
aur_pb() {  # version, sha256, extra line
    printf "pkgname=demo\npkgver=%s\npkgrel=1\narch=('x86_64')\nsource=('https://example.org/demo-\$pkgver.tar.gz'%s)\nsha256sums=('%s')\npackage() { :; }\n" "$1" "$3" "$2" > "$B/aur/demo.git/PKGBUILD"
    printf "pkgbase = demo\n\tpkgver = %s\n" "$1" > "$B/aur/demo.git/.SRCINFO"
    g add -A && g commit -qm "$1"
}
S1="$(printf 'a%.0s' {1..64})"; S2="$(printf 'b%.0s' {1..64})"
aur_pb 1.0 "$S1" ""; C1="$(g rev-parse HEAD)"
aur_pb 1.1 "$S2" ""; C2="$(g rev-parse HEAD)"
aur_pb 1.2 "$S2" " 'helper.sh'"; C3="$(g rev-parse HEAD)"
{ printf "# Copied from the AUR: https://aur.archlinux.org/demo.git\n# aur-commit: %s (1.0-1, 2026-01-01)\n# Reviewed 2026-01-01 by Vulcan: test.\n# Update: scripts/dev/bump-aur.sh demo\n" "$C1"
  git -C "$B/aur/demo.git" show "$C1:PKGBUILD"; } > "$B/root/pkgs/aur/demo/PKGBUILD"
cp "$B/root/pkgs/aur/demo/PKGBUILD" "$B/pinned"
BUMP="$B/root/scripts/dev/bump-aur.sh"
bump() { AUR_URL="file://$B/aur" bash "$BUMP" "$@" > "$B/out" 2>&1; }
rc=0; bump --check demo || rc=$?
if ! { [[ $rc == 1 ]] && grep -q "BEHIND  demo: pinned ${C1:0:7}.*2 newer" "$B/out"; }; then abad "bump --check: want BEHIND and exit 1, got $rc: $(cat "$B/out")"; fi
rc=0; bump demo --commit "$C2" --yes || rc=$?
if ! { [[ $rc == 2 ]] && grep -q -- "--reviewer" "$B/out"; }; then abad "bump without --reviewer: want exit 2, got $rc"; fi
# our download disagrees with the AUR's checksum: refuse
rc=0; BUMP_SUMS_CMD=':' bump demo --reviewer Tester --commit "$C2" --yes || rc=$?
if ! { [[ $rc == 4 ]] && grep -q "is not what we downloaded" "$B/out"; }; then abad "bump with a checksum that disagrees: want exit 4, got $rc: $(tail -3 "$B/out")"; fi
cp "$B/pinned" "$B/root/pkgs/aur/demo/PKGBUILD"
# version and checksum only: applied, sums recomputed (simulated), header moved
rc=0; BUMP_SUMS_CMD="sed -i 's/$S1/$S2/' \"\$1/PKGBUILD\"" bump demo --reviewer Tester --commit "$C2" --yes || rc=$?
P="$B/root/pkgs/aur/demo/PKGBUILD"
if [[ $rc == 0 ]] && grep -qx 'pkgver=1.1' "$P" && grep -q "^# aur-commit: $C2 (1.1-1, " "$P" \
    && grep -q "^# Reviewed $(date -u +%Y-%m-%d) by Tester: test.$" "$P" && grep -qF "'$S2'" "$P" \
    && grep -q "AUR's diff" "$B/out"; then :; else
    abad "bump of version and checksum: rc $rc; $(head -4 "$P" | paste -sd'|'); $(tail -3 "$B/out")"
fi
rc=0; AUR_URL="file://$B/aur" bash "$BUMP" --check demo > "$B/out" 2>&1 || rc=$?
if ! { [[ $rc == 1 ]] && grep -q "1 newer" "$B/out"; }; then abad "bump --check after moving to C2: want 1 newer commit, got $rc: $(cat "$B/out")"; fi
# the AUR added a source: stop for a hand merge, change nothing
cp "$P" "$B/before"
rc=0; BUMP_SUMS_CMD=':' bump demo --reviewer Tester --commit "$C3" --yes || rc=$?
if ! { [[ $rc == 3 ]] && grep -q "more than the version and checksums" "$B/out" && grep -q "helper.sh" "$B/out" && cmp -s "$P" "$B/before"; }; then
    abad "bump of a structural change: want exit 3 and no edit, got $rc: $(tail -4 "$B/out")"
fi
# Regression, bump-sig-skip (2026-09-30): updpkgsums writes SKIP for
# signature files; bump-aur.sh must pin them like every other source.
eval "$(sed -n '/^pin_signature_sums() {/,/^}/p' "$REPO/scripts/dev/bump-aur.sh")"
SK="$TMP/sigskip"; mkdir -p "$SK/src"
printf 'tarball' > "$SK/src/demo-1.tar.gz"; printf 'signature' > "$SK/src/demo-1.tar.gz.asc"
S_T="$(printf 'tarball' | sha256sum | cut -d' ' -f1)"; S_A="$(printf 'signature' | sha256sum | cut -d' ' -f1)"
printf "pkgname=demo\nsource=(\"demo-1.tar.gz::https://x/demo-1.tar.gz\"\n        \"demo-1.tar.gz.asc::https://x/demo-1.tar.gz.asc\")\nsha256sums=('%s'\n            'SKIP')\nvalidpgpkeys=('X')\n" "$S_T" > "$SK/PKGBUILD"
( cd "$SK" && SRCDEST="$SK/src" pin_signature_sums )
if [[ "$(bash -c 'source "$1"; echo "${sha256sums[*]}"' _ "$SK/PKGBUILD")" != "$S_T $S_A" ]] || ! grep -q "^validpgpkeys=('X')" "$SK/PKGBUILD"; then
    abad "bump-sig-skip: signature checksum not pinned: $(cat "$SK/PKGBUILD")"
fi
[[ $a_fail == 0 ]] && ok "$(find "$REPO/pkgs/aur" -name PKGBUILD | wc -l) AUR pins: commit, review and update lines, no SKIP, signers' keys match; bump-aur.sh check, apply, refusals"
echo

# shellcheck source=tests/pkgs/runtime.sh
. "$HERE/runtime.sh"
# shellcheck source=tests/pkgs/sys.sh
. "$HERE/sys.sh"
# shellcheck source=tests/pkgs/firstboot.sh
. "$HERE/firstboot.sh"

if [[ $fail == 0 ]]; then echo "ALL PASSED"; else echo "SOME TESTS FAILED"; fi
exit $fail
